<?xml version="1.0" encoding="utf-8"?>
<Database Name="RoleSys" Class="DataSysDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost\sql2005;Initial Catalog=RoleSys;Persist Security Info=True;User ID=sa" SettingsObjectName="Voodoo.Business.Properties.Settings" SettingsPropertyName="RoleSysConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[Group]" Member="Group">
    <Type Name="Group">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Group_User" Member="User" ThisKey="Id" OtherKey="GroupId" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="User">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserPassword" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GroupId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Sex" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Birthday" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Commission" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Group_User" Member="Group" ThisKey="GroupId" OtherKey="Id" Type="Group" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GroupMenuRelation" Member="GroupMenuRelation">
    <Type Name="GroupMenuRelation">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GroupId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SysPartId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AllowView" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AllowDelete" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AllowEdit" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AllowAdd" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ZTools" Member="ZTools">
    <Type Name="ZTools">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SysPart" Member="SysPart">
    <Type Name="SysPart">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MenuTitle" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Display" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MenuGroup" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ZWorkType" Member="ZWorkType">
    <Type Name="ZWorkType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ZWorkLog" Member="ZWorkLog">
    <Type Name="ZWorkLog">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomerName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Sex" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Tel" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MobilePhone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WorkTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="WorkContent" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="HomeName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="WorkHour" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EmployeesIds" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EmployeesNames" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ToolIds" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PayMoney" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="IsDelete" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsFinished" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Customerappraise" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ZCustomer" Member="ZCustomer">
    <Type Name="ZCustomer">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Sex" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Tel" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MobilePhone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HomeName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ValidateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CardNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UsedHour" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LeftHour" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDCard" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsReg" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ZEmployees" Member="ZEmployees">
    <Type Name="ZEmployees">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Sex" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Birthday" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Tel" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MobilePhone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="JoinTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="WorkAble" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="SalaryDegree" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsFree" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="UserType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ZPayLog" Member="ZPayLog">
    <Type Name="ZPayLog">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OperUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PayMoney" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="PayHour" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EmployeesId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ZWorkEmployeesRelation" Member="ZWorkEmployeesRelation">
    <Type Name="ZWorkEmployeesRelation">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmployeesId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WorkLogId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Salary" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
    </Type>
  </Table>
</Database>