<?xml version="1.0" encoding="utf-8"?>
<Database Name="RoleSys" Class="DataSysDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost\sql2005;Initial Catalog=RoleSys;Persist Security Info=True;User ID=sa" SettingsObjectName="Voodoo.Business.Properties.Settings" SettingsPropertyName="RoleSysConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[Group]" Member="Group">
    <Type Name="Group">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Group_User" Member="User" ThisKey="Id" OtherKey="GroupId" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.GroupMenuRelation" Member="GroupMenuRelation">
    <Type Name="GroupMenuRelation">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GroupId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SysPartId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AllowView" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AllowDelete" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AllowEdit" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AllowAdd" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ZTools" Member="ZTools">
    <Type Name="ZTools">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SysPart" Member="SysPart">
    <Type Name="SysPart">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MenuTitle" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Display" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MenuGroup" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ZWorkType" Member="ZWorkType">
    <Type Name="ZWorkType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ZWorkLog" Member="ZWorkLog">
    <Type Name="ZWorkLog">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomerName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Sex" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Tel" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MobilePhone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WorkTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="WorkContent" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="HomeName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="WorkHour" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EmployeesIds" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EmployeesNames" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ToolIds" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PayMoney" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="IsDelete" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsFinished" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Customerappraise" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Association Name="ZWorkLog_ZWorkEmployeesRelation" Member="ZWorkEmployeesRelation" ThisKey="Id" OtherKey="WorkLogId" Type="ZWorkEmployeesRelation" />
      <Association Name="ZWorkLog_ZCustomerBorrowLog" Member="ZCustomerBorrowLog" ThisKey="Id" OtherKey="WorkLogId" Type="ZCustomerBorrowLog" />
    </Type>
  </Table>
  <Table Name="dbo.ZEmployees" Member="ZEmployees">
    <Type Name="ZEmployees">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Sex" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Birthday" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Tel" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MobilePhone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="JoinTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="WorkAble" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="SalaryDegree" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsFree" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="UserType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="ZEmployees_ZWorkEmployeesRelation" Member="ZWorkEmployeesRelation" ThisKey="Id" OtherKey="EmployeesId" Type="ZWorkEmployeesRelation" />
      <Association Name="ZEmployees_ZHandBill" Member="ZHandBill" ThisKey="Id" OtherKey="Userid" Type="ZHandBill" />
    </Type>
  </Table>
  <Table Name="dbo.ViewUserWorkLog" Member="ViewUserWorkLog">
    <Type Name="ViewUserWorkLog">
      <Column Name="EmployeesId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Salary" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="WorkLogId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SalaryDegree" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WorkContent" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="CustomerId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomerName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WorkTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsFinished" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDelete" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ViewPayCard" Member="ViewPayCard">
    <Type Name="ViewPayCard">
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PayMoney" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="PayHour" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EmployeesId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CardNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PayTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Sex" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SalaryDegree" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ZPayLog" Member="ZPayLog">
    <Type Name="ZPayLog">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OperUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PayMoney" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="PayHour" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EmployeesId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CardNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PayTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="VTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ZWorkEmployeesRelation" Member="ZWorkEmployeesRelation">
    <Type Name="ZWorkEmployeesRelation">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmployeesId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WorkLogId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Salary" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Association Name="ZEmployees_ZWorkEmployeesRelation" Member="ZEmployees" ThisKey="EmployeesId" OtherKey="Id" Type="ZEmployees" IsForeignKey="true" />
      <Association Name="ZWorkLog_ZWorkEmployeesRelation" Member="ZWorkLog" ThisKey="WorkLogId" OtherKey="Id" Type="ZWorkLog" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ZCard" Member="ZCard">
    <Type Name="ZCard">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CardNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HourSum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HourLeft" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="ZCard_ZCardConsume" Member="ZCardConsume" ThisKey="Id" OtherKey="CardId" Type="ZCardConsume" />
      <Association Name="ZCard_ZCustomer" Member="ZCustomer" ThisKey="Id" OtherKey="CardID" Type="ZCustomer" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="User">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserPassword" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GroupId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Sex" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Birthday" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Commission" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Salary" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Association Name="Group_User" Member="Group" ThisKey="GroupId" OtherKey="Id" Type="Group" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ViewOfficerSalary" Member="ViewOfficerSalary">
    <Type Name="ViewOfficerSalary">
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="月份" Type="System.String" DbType="NVarChar(101)" CanBeNull="true" />
      <Column Name="总借款" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="底薪" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="应发" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ZBorrowSalary" Member="ZBorrowSalary">
    <Type Name="ZBorrowSalary">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BorrowTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BorrowMoney" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BorrowType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ZHandBill" Member="ZHandBill">
    <Type Name="ZHandBill">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DiliverCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ViewCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BackCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WorkTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Userid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="ZEmployees_ZHandBill" Member="ZEmployees" ThisKey="Userid" OtherKey="Id" Type="ZEmployees" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ViewXuanchuanSalary" Member="ViewXuanchuanSalary">
    <Type Name="ViewXuanchuanSalary">
      <Column Name="Userid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="发卡" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="查卡" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="回收" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="月份" Type="System.String" DbType="NVarChar(101)" CanBeNull="true" />
      <Column Name="发卡提成" Type="System.Decimal" DbType="Decimal(13,2)" CanBeNull="true" />
      <Column Name="查卡提成" Type="System.Decimal" DbType="Decimal(13,2)" CanBeNull="true" />
      <Column Name="回收提成" Type="System.Decimal" DbType="Decimal(13,2)" CanBeNull="true" />
      <Column Name="提成" Type="System.Decimal" DbType="Decimal(15,2)" CanBeNull="true" />
      <Column Name="借款" Type="System.Decimal" DbType="Decimal(38,2) NOT NULL" CanBeNull="false" />
      <Column Name="应发" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ViewBaojieSalary" Member="ViewBaojieSalary">
    <Type Name="ViewBaojieSalary">
      <Column Name="EmployeesId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="提成" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="月份" Type="System.String" DbType="NVarChar(101)" CanBeNull="true" />
      <Column Name="借款" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="罚款" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="应发" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ViewBaojieWorkDetail" Member="ViewBaojieWorkDetail">
    <Type Name="ViewBaojieWorkDetail">
      <Column Name="工时" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="保洁员" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="时间" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="任务" Type="System.String" DbType="NVarChar(2051)" CanBeNull="true" />
      <Column Name="日期" Type="System.String" DbType="NVarChar(101)" CanBeNull="true" />
      <Column Name="金额" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ViewXuanchuanWorkDetail" Member="ViewXuanchuanWorkDetail">
    <Type Name="ViewXuanchuanWorkDetail">
      <Column Name="发卡" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="查卡" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="回收" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="发卡提成" Type="System.Decimal" DbType="Decimal(13,2)" CanBeNull="true" />
      <Column Name="查卡提成" Type="System.Decimal" DbType="Decimal(13,2)" CanBeNull="true" />
      <Column Name="回收提成" Type="System.Decimal" DbType="Decimal(13,2)" CanBeNull="true" />
      <Column Name="总计" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="宣传员" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="时间" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="日期" Type="System.String" DbType="NVarChar(101)" CanBeNull="true" />
      <Column Name="类型" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="备注" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ZCardConsume" Member="ZCardConsume">
    <Type Name="ZCardConsume">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CardId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CardNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ConsumeHour" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ConsumeTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="ZCard_ZCardConsume" Member="ZCard" ThisKey="CardId" OtherKey="Id" Type="ZCard" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ZCustomer" Member="ZCustomer">
    <Type Name="ZCustomer">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Sex" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Tel" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MobilePhone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HomeName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ValidateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CardID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CardNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UsedHour" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LeftHour" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDCard" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsReg" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="ZCard_ZCustomer" Member="ZCard" ThisKey="CardID" OtherKey="Id" Type="ZCard" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ZCustomerBorrowLog" Member="ZCustomerBorrowLog">
    <Type Name="ZCustomerBorrowLog">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="WorkLogId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BorrowHour" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="BorrowTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HasPay" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PayTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="ZWorkLog_ZCustomerBorrowLog" Member="ZWorkLog" ThisKey="WorkLogId" OtherKey="Id" Type="ZWorkLog" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ViewWorkLogList" Member="ViewWorkLogList">
    <Type Name="ViewWorkLogList">
      <Column Name="WorkLogId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="users" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CustomerId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomerName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Sex" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Tel" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MobilePhone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WorkTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="WorkContent" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="HomeName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="WorkHour" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EmployeesIds" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EmployeesNames" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ToolIds" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PayMoney" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="IsDelete" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsFinished" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Customerappraise" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="borrowHour" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ViewCustomerList" Member="ViewCustomerList">
    <Type Name="ViewCustomerList">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Sex" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Tel" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MobilePhone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HomeName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ValidateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CardID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CardNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UsedHour" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LeftHour" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDCard" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsReg" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BorrowMoney" Type="System.Decimal" DbType="Decimal(38,2) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>